### PR TITLE
Add YAML support

### PR DESCRIPTION
**Pull request by ghost**
- support YAML docs
- support int values
- rename command, because it's not json-only anymore

### CODE REVIEW

**Comment by dottedmag** [comment]
This change is [Reviewable](https://reviewable.io/reviews/ridge/tj/5)

**Review by dottedmag — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 2 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/ridge/tj/5)* status: all files reviewed; 1 unresolved discussion (waiting on @wojciech-ridge)

___
*[doc2go/main.go, line 63 at r5](https://reviewable.io/reviews/ridge/tj/5#-MLqQYRY2omVQD9kJUtd:-MLqQYRY2omVQD9kJUte:bcsvpfy) ([raw file](https://github.com/ridge/tj/blob/4e15703a5c67ec0fe423dad0bd890443786f2338/doc2go/main.go#L63)):*
> ```Go
> }
> 
> func convertYAML(i interface{}) interface{} {
> ```

I'd call it something like `stringifyYAMLMapKeys` (bad name, please find a better one!) — it took me quite a while to understand what's happening here.

**Review by ghost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ridge/tj/5)* status: 1 of 3 files unreviewed; 1 unresolved discussion (waiting on @dottedmag and @feldgendler)

___
*[doc2go/main.go, line 63 at r5](https://reviewable.io/reviews/ridge/tj/5#-MLqQYRY2omVQD9kJUtd:-MLqRz0d3sYN5eScqOVx:b-896fix) ([raw file](https://github.com/ridge/tj/blob/4e15703a5c67ec0fe423dad0bd890443786f2338/doc2go/main.go#L63)):*
<details><summary><i>Previously, dottedmag (Misha Gusarov) wrote…</i></summary><blockquote>

I'd call it something like `stringifyYAMLMapKeys` (bad name, please find a better one!) — it took me quite a while to understand what's happening here.
</blockquote></details>

Done.

**Review by dottedmag — COMMENTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/ridge/tj/5)* status: :shipit: complete! all files reviewed; all discussions resolved

**Pull request merged**
